name: Build and Deploy mdBook

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  mdbook-build-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Test Markdown Files
        id: md-test
        run: mdbook test

      - name: Build mdBook
        run: mdbook build

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
