name: Build and Test mdBook

on:
  pull_request:
    branches: [master]

jobs:
  mdbook-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Test Markdown Files
        id: md-test
        run: mdbook test
